In [2]:
import numpy as np
myarr=np.array([1,2,3,5,7,99])


In [31]:
print(myarr.shape)

(6,)


In [37]:
np.array({23,43,55})

array({43, 23, 55}, dtype=object)

**zeros**

In [39]:
zeros

<class 'NameError'>: name 'zeros' is not defined

In [22]:
zeros.shape

<class 'NameError'>: name 'zeros' is not defined

In [23]:
zeros.dtype

<class 'NameError'>: name 'zeros' is not defined

In [6]:
ide=np.identity(4)
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
rng=np.arange(18)

In [9]:
rng.reshape(2,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [17]:
rng.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [43]:
lnspace=np.linspace(1,9,15)

In [44]:
lnspace

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        , 5.57142857, 6.14285714,
       6.71428571, 7.28571429, 7.85714286, 8.42857143, 9.        ])

In [47]:
a=np.array([1],[2],[3]])
b=np.array([1,2,3])
print(a+b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [51]:
a=np.array([[1],[2],[3]])
b=np.array([[1,2,3],[0]])
print(a+b)

<class 'ValueError'>: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [12]:
arr=np.arange(45)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [14]:
arr=arr.reshape(15,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [18]:
arr.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])